
--SQL QUESTIONS

--1. What is the total revenue generated by olist,Find the Average Order Value (AOV) for each customer state. 

SELECT ROUND(SUM(p.payment_value),2) AS Total_Revenue
FROM olist_order_payments_dataset AS p
JOIN olist_orders_dataset o ON p.order_id=o.order_id
WHERE order_status_updated !='Cancelled';

-- Average Order Value (AOV) for each customer state
SELECT c.customer_state, 
	ROUND(SUM(oi.price)/COUNT(DISTINCT oi.order_id),2) AS avg_order_value,
	COUNT(DISTINCT oi.order_id) as Total_order, 
	SUM(oi.price) as total_rev
FROM olist_customers_dataset AS c
JOIN olist_orders_dataset o ON c.customer_id=o.customer_id
JOIN olist_order_items_dataset oi ON o.order_id=oi.order_id
	WHERE O.order_status_updated !='Cancelled'
	GROUP BY c.customer_state
	order by avg_order_value desc;

--2. Calculate the monthly revenue and month-over-month revenue growth.

--monthly revenue
select extract(month from o.order_purchase_timestamp) as months,
		extract(year from o.order_purchase_timestamp) as years,
	sum(oi.price) FROM olist_orders_dataset o
	join olist_order_items_dataset oi on o.order_id=oi.order_id
WHERE o.order_status_updated !='Cancelled'
group by extract(month from o.order_purchase_timestamp),
extract(year from o.order_purchase_timestamp)
order by years,months;

--MoM revenue growth
WITH monthly_growth AS (SELECT DATE_TRUNC('month',o.order_purchase_timestamp)::date AS months,
	SUM(oi.price) AS total_rev FROM olist_products_dataset AS pc
JOIN olist_order_items_dataset oi ON pc.product_id=oi.product_id
JOIN olist_orders_dataset o ON oi.order_id=o.order_id
	WHERE o.order_status_updated !='Cancelled'
	GROUP BY 1)
SELECT  months,total_rev,
COALESCE(LAG(total_rev) OVER ( ORDER BY months ),0) AS prev_monthly_rev
FROM monthly_growth;

-- 3 Analyze how customer payment preferences have shifted by year over the dataset's lifespan.

SELECT DATE_TRUNC('year',o.order_purchase_timestamp)::DATE AS years,
p.payment_type,
COUNT(*) AS total_payment
FROM olist_orders_dataset AS o
JOIN olist_order_payments_dataset p ON o.order_id=p.order_id
GROUP BY DATE_TRUNC('year',o.order_purchase_timestamp),p.payment_type
ORDER BY years,total_payment desc ; 

-- 4 which is the top selling product category? determine their contribution to overall sales.

SELECT  p.product_category_name,
		COUNT(*) AS total_sold,
		ROUND(SUM(oi.price)) AS rev,
	ROUND(100*SUM(oi.price)/SUM(SUM(oi.price)) OVER (),2)   AS sales_rev_pct,
	DENSE_RANK() OVER (order by SUM(oi.price) DESC) as ranks
FROM olist_products_dataset p
JOIN olist_order_items_dataset oi ON p.product_id=oi.product_id
	GROUP BY p.product_category_name
	order by rev desc
	LIMIT 10;

-- 5 Identify the specific sellers who contribute to the top 80% of total gross revenue.

SELECT * FROM
( SELECT seller_id,total,
ROUND(100*SUM(total) OVER (ORDER BY total DESC)/SUM(total) OVER (),2) AS PCT
FROM (SELECT seller_id,SUM(price) AS total
FROM olist_order_items_dataset
GROUP BY seller_id)
)
WHERE pct <=80
ORDER BY total desc;

-- 6 Identify which two distinct product categories are most frequently purchased together in the exact same order.

WITH category AS (SELECT distinct oi.order_id,
		p.product_category_name
	FROM olist_order_items_dataset oi
JOIN olist_products_dataset p on oi.product_id=p.product_id)
	select a.product_category_name AS c1,
	b.product_category_name AS c2,
	COUNT(*) AS order_together
FROM category a
JOIN category b     --Self Join
ON a.order_id=b.order_id AND a.product_category_name < b.product_category_name
GROUP BY a.product_category_name,
b.product_category_name
ORDER BY order_together DESC
LIMIT 1;

-- 7  what percentage of orders are delivered after the estimated delivery date, broken down by the customer's state.

SELECT c.customer_state,COUNT(*) AS total_orders,
COUNT(*) FILTER(WHERE  o.order_delivered_customer_date >o.order_estimated_delivery_date) AS late_orders,
ROUND(COUNT(CASE WHEN o.order_delivered_customer_date >o.order_estimated_delivery_date THEN 1 END )*100/
COUNT(*),2) AS late_orders_pct 
FROM olist_orders_dataset O
JOIN olist_customers_dataset C ON o.customer_id=c.customer_id
WHERE order_status_updated='Delivered' AND o.order_delivered_customer_date IS NOT NULL 
AND o.order_estimated_delivery_date IS NOT NULL
GROUP BY c.customer_state
ORDER BY late_orders_pct DESC;


-- 8 which product category have freight costs that are disproportionately higher

SELECT p.product_category_name,
SUM(oi.price) AS total_rev,
SUM(oi.freight_value) AS total_shipping_cost,
ROUND(SUM(oi.freight_value)/SUM(oi.price)*100,2) AS pct
FROM olist_order_items_dataset oi
JOIN olist_products_dataset p ON oi.product_id=p.product_id
WHERE p.product_category_name IS NOT NULL
GROUP BY 1
ORDER BY pct DESC;

-- 9 does faster deliveries result in higher review scores. Categorize delivery times into 'Early', 'On Time', and 'Late', and calculate the average review score for each bucket.

SELECT 
CASE WHEN o.order_delivered_customer_date < o.order_estimated_delivery_date THEN 'EARLY'
WHEN o.order_delivered_customer_date = o.order_estimated_delivery_date THEN 'ON-TIME'
WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 'LATE' END AS bucket,
ROUND(AVG(r.review_score),2) AS avg_review_score
FROM  olist_orders_dataset o 
JOIN olist_order_reviews_dataset r ON o.order_id=r.order_id
WHERE o.order_status_updated='Delivered' AND o.order_delivered_customer_date IS NOT NULL
GROUP BY bucket
ORDER BY avg_review_score DESC;

--10 Segment all customers into 4 tiers (Platinum, Gold, Silver, Bronze) based on their Recency (days since last order), Frequency (number of orders), and Monetary value (total spend).

WITH max_date AS
(SELECT MAX(order_purchase_timestamp)::DATE AS last_date
FROM olist_orders_dataset
),
rfm AS (SELECT c.customer_unique_id,
md.last_date - MAX(o.order_purchase_timestamp)::DATE AS recency,
COUNT(DISTINCT o.order_id) AS frequency,
SUM(p.payment_value) AS monetary
	FROM olist_customers_dataset c
	JOIN olist_orders_dataset o ON c.customer_id=o.customer_id
	JOIN olist_order_payments_dataset p ON o.order_id=p.order_id
	CROSS JOIN max_date md
	WHERE order_status_updated='Delivered'
	GROUP BY c.customer_unique_id,md.last_date
),
rfm_score AS (SELECT *,
	NTILE(4) OVER (ORDER BY recency DESC) AS recency_score,
	NTILE(4) OVER (ORDER BY frequency) AS frequency_score,
	NTILE(4) OVER (ORDER BY monetary) AS monetary_score
	FRom rfm
)
SELECT customer_unique_id,
		recency,
		frequency,
		monetary,
		recency_score,
		frequency_score,
		monetary_score,
		recency_score+frequency_score+monetary_score AS total_score,
	CASE
	WHEN recency_score+frequency_score+monetary_score>= 10 THEN 'Platinum' 
	WHEN recency_score+frequency_score+monetary_score>= 7 THEN 'gold' 
	WHEN recency_score+frequency_score+monetary_score>= 5 THEN 'silver' 
	ELSE 'Bronze' END AS tier
	FROM rfm_score
	ORDER BY total_score DESC;
	



